// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/capital" | "/dashboard/customers" | "/dashboard/customers/[id]" | "/dashboard/expenses" | "/dashboard/movements" | "/dashboard/movements/[id]/edit" | "/dashboard/movements/new" | "/dashboard/open" | "/dashboard/rates" | "/dashboard/reports" | "/dashboard/reports/daily" | "/dashboard/transactions" | "/dashboard/transactions/[id]" | "/dashboard/transactions/[id]/edit" | "/dashboard/transactions/new" | "/dashboard/users" | "/login"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/capital" | "/api/capital/[id]" | "/api/capital/close" | "/api/customers" | "/api/customers/[id]" | "/api/expenses" | "/api/expenses/[id]" | "/api/movements" | "/api/movements/[id]" | "/api/rates" | "/api/reports/excel" | "/api/reports/pdf" | "/api/statements/customer/[id]" | "/api/transactions" | "/api/transactions/[id]" | "/api/transactions/[id]/executions" | "/api/transactions/executions/[id]" | "/api/users" | "/api/users/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/capital": {}
  "/api/capital/[id]": { "id": string; }
  "/api/capital/close": {}
  "/api/customers": {}
  "/api/customers/[id]": { "id": string; }
  "/api/expenses": {}
  "/api/expenses/[id]": { "id": string; }
  "/api/movements": {}
  "/api/movements/[id]": { "id": string; }
  "/api/rates": {}
  "/api/reports/excel": {}
  "/api/reports/pdf": {}
  "/api/statements/customer/[id]": { "id": string; }
  "/api/transactions": {}
  "/api/transactions/[id]": { "id": string; }
  "/api/transactions/[id]/executions": { "id": string; }
  "/api/transactions/executions/[id]": { "id": string; }
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/dashboard": {}
  "/dashboard/capital": {}
  "/dashboard/customers": {}
  "/dashboard/customers/[id]": { "id": string; }
  "/dashboard/expenses": {}
  "/dashboard/movements": {}
  "/dashboard/movements/[id]/edit": { "id": string; }
  "/dashboard/movements/new": {}
  "/dashboard/open": {}
  "/dashboard/rates": {}
  "/dashboard/reports": {}
  "/dashboard/reports/daily": {}
  "/dashboard/transactions": {}
  "/dashboard/transactions/[id]": { "id": string; }
  "/dashboard/transactions/[id]/edit": { "id": string; }
  "/dashboard/transactions/new": {}
  "/dashboard/users": {}
  "/login": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
